# Generated by Django 3.2.6 on 2022-06-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='Cars',
            new_name='cars',
        ),
    ]
