# Generated by Django 3.2.6 on 2022-06-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_cars_list_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='cars',
        ),
    ]
