# Generated by Django 3.2.6 on 2022-06-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_list_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='News_paper',
            new_name='News_Paper',
        ),
    ]
