# Generated by Django 3.2.6 on 2022-06-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_news_paper_list_news_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='cars',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='list',
            name='News_Paper',
            field=models.CharField(default='', max_length=150),
        ),
    ]
